name: SweetCheckout
version: '${version}'
main: top.mrxiaom.sweet.checkout.SweetCheckout
api-version: 1.13
depend: []
softdepend:
  - PlaceholderAPI
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetcheckout:
    description: 'The main command of SweetCheckout'
    aliases: [ checkout, cz ]
